import {makeGroundMaterial,makeBarkMaterial,makeRuneMaterial} from './graphics.js';
const rand=(a,b)=>a+Math.random()*(b-a);
export function buildWorld(THREE,scene){const world=new THREE.Group();scene.add(world);const size=180,seg=100,geo=new THREE.PlaneGeometry(size,size,seg,seg);geo.rotateX(-Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,Math.sin(x*.055)*1.9+Math.cos(z*.047)*1.5+Math.sin((x+z)*.09)*.55+Math.cos(x*.17)*Math.sin(z*.13)*.28);}geo.computeVertexNormals();const ground=new THREE.Mesh(geo,makeGroundMaterial(THREE));ground.receiveShadow=true;world.add(ground);
const trunkMat=makeBarkMaterial(THREE),leafMat=new THREE.MeshStandardMaterial({color:0x31573a,roughness:.88}),stoneMat=new THREE.MeshStandardMaterial({color:0x555d58,roughness:.9}),runeMat=makeRuneMaterial(THREE);const trunkGeo=new THREE.CylinderGeometry(.22,.42,3.3,9),leafGeo=new THREE.IcosahedronGeometry(1.55,2),rockGeo=new THREE.DodecahedronGeometry(1.5,1);for(let i=0;i<95;i++){const x=rand(-78,78),z=rand(-78,78);if(Math.hypot(x,z)<10)continue;const y=heightAt(x,z);const tree=new THREE.Group();const trunk=new THREE.Mesh(trunkGeo,trunkMat);trunk.position.y=1.6;trunk.castShadow=true;tree.add(trunk);for(let k=0;k<3;k++){const crown=new THREE.Mesh(leafGeo,leafMat);crown.position.set(rand(-.45,.45),2.6+k*.45,rand(-.4,.4));crown.scale.set(rand(.72,1.05),rand(.8,1.25),rand(.72,1.05));crown.castShadow=true;tree.add(crown);}tree.position.set(x,y,z);tree.rotation.y=rand(0,6.28);world.add(tree);}
for(let i=0;i<26;i++){const x=rand(-70,70),z=rand(-70,70);if(Math.hypot(x,z)<12)continue;const rock=new THREE.Mesh(rockGeo,stoneMat);rock.position.set(x,heightAt(x,z)+.7,z);rock.scale.set(rand(.7,1.5),rand(.55,1.15),rand(.7,1.4));rock.rotation.set(rand(-.3,.3),rand(0,6.28),rand(-.2,.2));rock.castShadow=true;rock.receiveShadow=true;world.add(rock);if(i%3===0){const mark=new THREE.Mesh(new THREE.TorusGeometry(.42,.035,6,18),runeMat);mark.position.copy(rock.position);mark.position.y+=.6;mark.rotation.x=Math.PI/2;world.add(mark);}}
// Instanced grass blades: animated vertex shader bends each blade with world position.
const bladeGeo=new THREE.PlaneGeometry(.12,.72,1,3);bladeGeo.translate(0,.36,0);const grassMat=new THREE.MeshStandardMaterial({color:0x789b4c,side:THREE.DoubleSide,roughness:.9});grassMat.onBeforeCompile=shader=>{shader.uniforms.uTime={value:0};shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime;');shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nfloat wind=sin((instanceMatrix[3].x+instanceMatrix[3].z)*0.21+uTime*1.4);\ntransformed.x += wind * uv.y * 0.12;');grassMat.userData.shader=shader;};const count=3400,grass=new THREE.InstancedMesh(bladeGeo,grassMat,count),dummy=new THREE.Object3D();for(let i=0;i<count;i++){const x=rand(-84,84),z=rand(-84,84);dummy.position.set(x,heightAt(x,z)+.02,z);dummy.rotation.y=rand(0,6.28);const s=rand(.55,1.35);dummy.scale.set(s,s,s);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix); }grass.instanceMatrix.needsUpdate=true;world.add(grass);
// patterned camp shelter
const camp=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color:0x9a6841,roughness:.84,side:THREE.DoubleSide});const roof=new THREE.Mesh(new THREE.ConeGeometry(3.1,2.4,4),cloth);roof.position.y=2.3;roof.rotation.y=Math.PI/4;roof.castShadow=true;camp.add(roof);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.09,.12,3,8),trunkMat);pole.position.y=1.5;camp.add(pole);for(let i=0;i<4;i++){const stripe=new THREE.Mesh(new THREE.TorusGeometry(1.45,.035,4,32),runeMat);stripe.position.y=.9+i*.28;stripe.rotation.x=Math.PI/2;camp.add(stripe);}camp.position.set(7,heightAt(7,5),5);camp.rotation.y=.4;world.add(camp);
return {group:world,grass,update(t){if(grassMat.userData.shader)grassMat.userData.shader.uniforms.uTime.value=t;}};}
export function heightAt(x,z){return Math.sin(x*.055)*1.9+Math.cos(z*.047)*1.5+Math.sin((x+z)*.09)*.55+Math.cos(x*.17)*Math.sin(z*.13)*.28;}
